version: '3'

services:
  licensingservice:
    image: optima/licensing-service:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    networks:
      backend:
        aliases:
          - "licenseservice"
networks:
  backend:
    driver: bridge
